//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ConsultarPelículasOperationCompleted;
    
    private System.Threading.SendOrPostCallback RegistrarAlquilerOperationCompleted;
    
    private System.Threading.SendOrPostCallback RegistrarVentaOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://localhost:51575/Service1.asmx";
    }
    
    /// <remarks/>
    public event ConsultarPelículasCompletedEventHandler ConsultarPelículasCompleted;
    
    /// <remarks/>
    public event RegistrarAlquilerCompletedEventHandler RegistrarAlquilerCompleted;
    
    /// <remarks/>
    public event RegistrarVentaCompletedEventHandler RegistrarVentaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPelículas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable ConsultarPelículas(int codPelícula, string nomPelícula) {
        object[] results = this.Invoke("ConsultarPelículas", new object[] {
                    codPelícula,
                    nomPelícula});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginConsultarPelículas(int codPelícula, string nomPelícula, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ConsultarPelículas", new object[] {
                    codPelícula,
                    nomPelícula}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndConsultarPelículas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void ConsultarPelículasAsync(int codPelícula, string nomPelícula) {
        this.ConsultarPelículasAsync(codPelícula, nomPelícula, null);
    }
    
    /// <remarks/>
    public void ConsultarPelículasAsync(int codPelícula, string nomPelícula, object userState) {
        if ((this.ConsultarPelículasOperationCompleted == null)) {
            this.ConsultarPelículasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPelículasOperationCompleted);
        }
        this.InvokeAsync("ConsultarPelículas", new object[] {
                    codPelícula,
                    nomPelícula}, this.ConsultarPelículasOperationCompleted, userState);
    }
    
    private void OnConsultarPelículasOperationCompleted(object arg) {
        if ((this.ConsultarPelículasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ConsultarPelículasCompleted(this, new ConsultarPelículasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarAlquiler", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RegistrarAlquiler(int codPelícula, int codSocio) {
        this.Invoke("RegistrarAlquiler", new object[] {
                    codPelícula,
                    codSocio});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRegistrarAlquiler(int codPelícula, int codSocio, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RegistrarAlquiler", new object[] {
                    codPelícula,
                    codSocio}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRegistrarAlquiler(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void RegistrarAlquilerAsync(int codPelícula, int codSocio) {
        this.RegistrarAlquilerAsync(codPelícula, codSocio, null);
    }
    
    /// <remarks/>
    public void RegistrarAlquilerAsync(int codPelícula, int codSocio, object userState) {
        if ((this.RegistrarAlquilerOperationCompleted == null)) {
            this.RegistrarAlquilerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarAlquilerOperationCompleted);
        }
        this.InvokeAsync("RegistrarAlquiler", new object[] {
                    codPelícula,
                    codSocio}, this.RegistrarAlquilerOperationCompleted, userState);
    }
    
    private void OnRegistrarAlquilerOperationCompleted(object arg) {
        if ((this.RegistrarAlquilerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RegistrarAlquilerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RegistrarVenta(int codPelícula, int codSocio) {
        this.Invoke("RegistrarVenta", new object[] {
                    codPelícula,
                    codSocio});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRegistrarVenta(int codPelícula, int codSocio, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RegistrarVenta", new object[] {
                    codPelícula,
                    codSocio}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRegistrarVenta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void RegistrarVentaAsync(int codPelícula, int codSocio) {
        this.RegistrarVentaAsync(codPelícula, codSocio, null);
    }
    
    /// <remarks/>
    public void RegistrarVentaAsync(int codPelícula, int codSocio, object userState) {
        if ((this.RegistrarVentaOperationCompleted == null)) {
            this.RegistrarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarVentaOperationCompleted);
        }
        this.InvokeAsync("RegistrarVenta", new object[] {
                    codPelícula,
                    codSocio}, this.RegistrarVentaOperationCompleted, userState);
    }
    
    private void OnRegistrarVentaOperationCompleted(object arg) {
        if ((this.RegistrarVentaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RegistrarVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ConsultarPelículasCompletedEventHandler(object sender, ConsultarPelículasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConsultarPelículasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ConsultarPelículasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void RegistrarAlquilerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void RegistrarVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
