// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebSite {
	
	
	public partial class BuscarInventario {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox TBCódigo;
		
		protected System.Web.UI.WebControls.TextBox TBNombre;
		
		protected System.Web.UI.WebControls.Button BBuscar;
		
		protected System.Web.UI.WebControls.Label LBuscar;
		
		protected System.Web.UI.WebControls.GridView GVLista;
	}
}
